#!/bin/sh
# Xcode Cloud post-clone step.
#
# The .xcodeproj is generated by XcodeGen (not committed), so Xcode Cloud must
# install XcodeGen and generate the project before it builds. Release builds run
# here and ship to TestFlight, mirroring the snapper-ios pipeline.
set -e

echo "ci_post_clone: installing XcodeGen"
brew install xcodegen

# Trust the swift-openapi-generator build tool plugin in this non-interactive
# environment (otherwise: "Plugin 'OpenAPIGenerator' must be enabled before it
# can be used"). Equivalent to xcodebuild -skipPackagePluginValidation, which
# Xcode Cloud's managed build invocation does not let us pass.
defaults write com.apple.dt.Xcode IDESkipPackagePluginFingerprintValidatation -bool YES
defaults write com.apple.dt.Xcode IDESkipMacroFingerprintValidation -bool YES

echo "ci_post_clone: generating Vesta.xcodeproj"
cd "$CI_PRIMARY_REPOSITORY_PATH"
xcodegen generate

# Xcode Cloud disables automatic SPM resolution (even via -resolvePackageDependencies)
# and requires a committed Package.resolved. The .xcodeproj is generated (not
# committed), so drop the committed pin file into the generated workspace before
# the resolution/archive step.
echo "ci_post_clone: installing pinned Package.resolved"
mkdir -p Vesta.xcodeproj/project.xcworkspace/xcshareddata/swiftpm
cp ci_scripts/Package.resolved Vesta.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved

echo "ci_post_clone: done"
